<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MoniHop.Core\MoniHop.Core.csproj" />
    <ProjectReference Include="..\MoniHop.Windows\MoniHop.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="Assets\MoniHop.ico" />
    <Resource Include="Assets\MoniHop.Window.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);WFO0003</NoWarn>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MoniHop.ico</ApplicationIcon>
    <AssemblyName>MoniHop</AssemblyName>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

</Project>
